version: '3'
services:
  litespeed:
    image: litespeedtech/openlitespeed:1.7.18-lsphp81
    logging:
      driver: none
    env_file:
      - .env
    volumes:
      - ./lsws/conf:/usr/local/lsws/conf
      - ./lsws/admin-conf:/usr/local/lsws/admin/conf
      - ./bin/container:/usr/local/bin
      - ../:/usr/local/lsws/conf/vhosts/yeetnite_api/site
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      TZ: ${TimeZone}
    deploy:
      resources:
        limits:
          memory: 4096M
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  default:
    driver: bridge
