version: '3'
services:
  litespeed:
    image: litespeedtech/openlitespeed:1.7.18-lsphp81
    container_name: yeetnite_webserver
    logging:
      driver: none
    env_file:
      - .env
    volumes:
      - ./lsws/conf:/usr/local/lsws/conf
      - ./lsws/admin-conf:/usr/local/lsws/admin/conf
      - ./bin/container:/usr/local/bin
      - ../:/usr/local/lsws/conf/vhosts/yeetnite_api/site
    links:
      - memcached
    ports:
      - 1880:80
      - 8443:443
    restart: always
    environment:
      TZ: ${TimeZone}
    deploy:
      resources:
        limits:
          memory: 4096M
    networks:
      - default
  memcached:
    image: memcached:1.6.22-alpine3.18
    container_name: yeetnite_memcached
    networks:
      - default
    logging:
      driver: none
    deploy:
      resources:
        limits:
          memory: 512M
networks:
  default:
    driver: bridge
